# coding: utf-8

"""
    GIPHY Public API

    A test of what Giphy API docs would look like in Gelato

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_gifs_categories_category_get(self):
        """
        Test case for gifs_categories_category_get

        Category Tags Endpoint.
        """
        pass

    def test_gifs_categories_category_tag_get(self):
        """
        Test case for gifs_categories_category_tag_get

        Tagged Gifs Endpoint.
        """
        pass

    def test_gifs_categories_get(self):
        """
        Test case for gifs_categories_get

        Categories Endpoint.
        """
        pass

    def test_gifs_get(self):
        """
        Test case for gifs_get

        Get GIFs by ID Endpoint
        """
        pass

    def test_gifs_gif_id_get(self):
        """
        Test case for gifs_gif_id_get

        Get GIF by ID Endpoint
        """
        pass

    def test_gifs_random_get(self):
        """
        Test case for gifs_random_get

        Random Endpoint
        """
        pass

    def test_gifs_search_get(self):
        """
        Test case for gifs_search_get

        Search Endpoint
        """
        pass

    def test_gifs_translate_get(self):
        """
        Test case for gifs_translate_get

        Translate Endpoint
        """
        pass

    def test_gifs_trending_get(self):
        """
        Test case for gifs_trending_get

        Trending GIFs Endpoint
        """
        pass

    def test_stickers_random_get(self):
        """
        Test case for stickers_random_get

        Random Sticker Endpoint
        """
        pass

    def test_stickers_search_get(self):
        """
        Test case for stickers_search_get

        Sticker Search Endpoint
        """
        pass

    def test_stickers_translate_get(self):
        """
        Test case for stickers_translate_get

        Sticker Translate Endpoint
        """
        pass

    def test_stickers_trending_get(self):
        """
        Test case for stickers_trending_get

        Trending Stickers Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
