# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.gif_images_downsized_large import GifImagesDownsizedLarge


class TestGifImagesDownsizedLarge(unittest.TestCase):
    """ GifImagesDownsizedLarge unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGifImagesDownsizedLarge(self):
        """
        Test GifImagesDownsizedLarge
        """
        model = giphy_client.models.gif_images_downsized_large.GifImagesDownsizedLarge()


if __name__ == '__main__':
    unittest.main()
