# coding: utf-8

"""
    GIPHY Public API

    A test of what Giphy API docs would look like in Gelato

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.gif_images_downsized_small import GifImagesDownsizedSmall


class TestGifImagesDownsizedSmall(unittest.TestCase):
    """ GifImagesDownsizedSmall unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGifImagesDownsizedSmall(self):
        """
        Test GifImagesDownsizedSmall
        """
        model = swagger_client.models.gif_images_downsized_small.GifImagesDownsizedSmall()


if __name__ == '__main__':
    unittest.main()
