# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.inline_response_400 import InlineResponse400


class TestInlineResponse400(unittest.TestCase):
    """ InlineResponse400 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400(self):
        """
        Test InlineResponse400
        """
        model = giphy_client.models.inline_response_400.InlineResponse400()


if __name__ == '__main__':
    unittest.main()
