# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.inline_response_200_4 import InlineResponse2004


class TestInlineResponse2004(unittest.TestCase):
    """ InlineResponse2004 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004(self):
        """
        Test InlineResponse2004
        """
        model = giphy_client.models.inline_response_200_4.InlineResponse2004()


if __name__ == '__main__':
    unittest.main()
