# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.user import User


class TestUser(unittest.TestCase):
    """ User unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser(self):
        """
        Test User
        """
        model = giphy_client.models.user.User()


if __name__ == '__main__':
    unittest.main()
