# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.gif_images_fixed_height_small_still import GifImagesFixedHeightSmallStill


class TestGifImagesFixedHeightSmallStill(unittest.TestCase):
    """ GifImagesFixedHeightSmallStill unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGifImagesFixedHeightSmallStill(self):
        """
        Test GifImagesFixedHeightSmallStill
        """
        model = giphy_client.models.gif_images_fixed_height_small_still.GifImagesFixedHeightSmallStill()


if __name__ == '__main__':
    unittest.main()
