# coding: utf-8

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import giphy_client
from giphy_client.rest import ApiException
from giphy_client.models.gif_images_looping import GifImagesLooping


class TestGifImagesLooping(unittest.TestCase):
    """ GifImagesLooping unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGifImagesLooping(self):
        """
        Test GifImagesLooping
        """
        model = giphy_client.models.gif_images_looping.GifImagesLooping()


if __name__ == '__main__':
    unittest.main()
