# coding: utf-8
#
# Created by David Hargat.
# Copyright © 2017 Giphy. All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.base_channel_model import BaseChannelModel
from .models.base_channel_model_gifs import BaseChannelModelGifs
from .models.breadcrumb import Breadcrumb
from .models.category import Category
from .models.channel_with_children_model import ChannelWithChildrenModel
from .models.channel_with_children_model_children import ChannelWithChildrenModelChildren
from .models.gif import Gif
from .models.gif_images import GifImages
from .models.gif_images_downsized import GifImagesDownsized
from .models.gif_images_downsized_large import GifImagesDownsizedLarge
from .models.gif_images_downsized_medium import GifImagesDownsizedMedium
from .models.gif_images_downsized_small import GifImagesDownsizedSmall
from .models.gif_images_downsized_still import GifImagesDownsizedStill
from .models.gif_images_fixed_height import GifImagesFixedHeight
from .models.gif_images_fixed_height_downsampled import GifImagesFixedHeightDownsampled
from .models.gif_images_fixed_height_small import GifImagesFixedHeightSmall
from .models.gif_images_fixed_height_small_still import GifImagesFixedHeightSmallStill
from .models.gif_images_fixed_height_still import GifImagesFixedHeightStill
from .models.gif_images_fixed_width import GifImagesFixedWidth
from .models.gif_images_fixed_width_downsampled import GifImagesFixedWidthDownsampled
from .models.gif_images_fixed_width_small import GifImagesFixedWidthSmall
from .models.gif_images_fixed_width_small_still import GifImagesFixedWidthSmallStill
from .models.gif_images_fixed_width_still import GifImagesFixedWidthStill
from .models.gif_images_looping import GifImagesLooping
from .models.gif_images_original import GifImagesOriginal
from .models.gif_images_original_still import GifImagesOriginalStill
from .models.gif_images_preview import GifImagesPreview
from .models.gif_images_preview_gif import GifImagesPreviewGif
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001
from .models.inline_response_200_2 import InlineResponse2002
from .models.inline_response_200_3 import InlineResponse2003
from .models.inline_response_200_4 import InlineResponse2004
from .models.inline_response_200_5 import InlineResponse2005
from .models.inline_response_400 import InlineResponse400
from .models.last_child_model import LastChildModel
from .models.last_child_model_children import LastChildModelChildren
from .models.meta_content import MetaContent
from .models.meta_object import MetaObject
from .models.pagination import Pagination
from .models.random_gif import RandomGif
from .models.shallow_tag import ShallowTag
from .models.tag import Tag
from .models.trending_tag import TrendingTag
from .models.user import User

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
