# coding: utf-8
#
# Created by David Hargat.
# Copyright © 2017 Giphy. All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""
    giphy-api

    Giphy's public api.

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .base_channel_model import BaseChannelModel
from .base_channel_model_gifs import BaseChannelModelGifs
from .breadcrumb import Breadcrumb
from .category import Category
from .channel_with_children_model import ChannelWithChildrenModel
from .channel_with_children_model_children import ChannelWithChildrenModelChildren
from .gif import Gif
from .gif_images import GifImages
from .gif_images_downsized import GifImagesDownsized
from .gif_images_downsized_large import GifImagesDownsizedLarge
from .gif_images_downsized_medium import GifImagesDownsizedMedium
from .gif_images_downsized_small import GifImagesDownsizedSmall
from .gif_images_downsized_still import GifImagesDownsizedStill
from .gif_images_fixed_height import GifImagesFixedHeight
from .gif_images_fixed_height_downsampled import GifImagesFixedHeightDownsampled
from .gif_images_fixed_height_small import GifImagesFixedHeightSmall
from .gif_images_fixed_height_small_still import GifImagesFixedHeightSmallStill
from .gif_images_fixed_height_still import GifImagesFixedHeightStill
from .gif_images_fixed_width import GifImagesFixedWidth
from .gif_images_fixed_width_downsampled import GifImagesFixedWidthDownsampled
from .gif_images_fixed_width_small import GifImagesFixedWidthSmall
from .gif_images_fixed_width_small_still import GifImagesFixedWidthSmallStill
from .gif_images_fixed_width_still import GifImagesFixedWidthStill
from .gif_images_looping import GifImagesLooping
from .gif_images_original import GifImagesOriginal
from .gif_images_original_still import GifImagesOriginalStill
from .gif_images_preview import GifImagesPreview
from .gif_images_preview_gif import GifImagesPreviewGif
from .inline_response_200 import InlineResponse200
from .inline_response_200_1 import InlineResponse2001
from .inline_response_200_2 import InlineResponse2002
from .inline_response_200_3 import InlineResponse2003
from .inline_response_200_4 import InlineResponse2004
from .inline_response_200_5 import InlineResponse2005
from .inline_response_400 import InlineResponse400
from .last_child_model import LastChildModel
from .last_child_model_children import LastChildModelChildren
from .meta_content import MetaContent
from .meta_object import MetaObject
from .pagination import Pagination
from .random_gif import RandomGif
from .shallow_tag import ShallowTag
from .tag import Tag
from .trending_tag import TrendingTag
from .user import User
